baseURL       : "https://adityam.github.io/linux-blog"

languageCode  : "en-us"
title         : Tinkering with Linux
author        : Aditya Mahajan
theme         : homepage

metaDataFormat: yaml
publishDir    : docs

rssLimit      : 10

params:
  disqus : "random-determinism"

markup:
  defaultMarkdownHandler: "blackfriday"

